import React, { createContext, useContext, useMemo } from 'react';
import { SupportedLanguage } from '../types/anlatiTypes';

type Copy = Record<string, string>;

const en: Copy = {
  'nav.portal': 'Home', 'nav.feed': 'Explore', 'nav.registry': 'Members', 'nav.chat': 'Messages', 'nav.profile': 'Profile', 'nav.events': 'Events',
  'nav.members': 'Members', 'nav.salons': 'Salons', 'nav.login': 'Sign in', 'nav.loginJoin': 'Sign in / Join', 'nav.compose': 'Compose dispatch',
  'home.eyebrow': 'Major Club · Société Privée', 'home.title': 'Desire has its own etiquette.',
  'home.intro': 'A private social community where adults meet like-minded people with privacy, mutual consent and grace.',
  'home.explore': 'Explore the community', 'home.join': 'Join for free', 'home.verified': 'Verified profiles', 'home.consent': 'Consent-led community', 'home.privacy': 'Privacy first',
  'home.peopleTitle': 'Who is here tonight?', 'home.peopleText': 'Online verified members are ranked from live catalogue data; the selection changes as the community moves.', 'home.allMembers': 'All members',
  'home.pathsTitle': 'There is more than one way in.', 'home.pathsText': 'Browse people and hear the community first; create your profile when you are ready.',
  'home.registryDescription': 'Discover verified profiles by city, proximity and shared interests.', 'home.registryAction': 'Browse members',
  'home.gazetteDescription': 'Photos, notes and open conversations shared by the community.', 'home.gazetteAction': 'View the Gazette',
  'home.dispatchDescription': 'Quiet, direct conversations reserved for the people you connect with.', 'home.dispatchAction': 'Enter the salons',
  'home.ethosTitle': 'Attraction may be mysterious. Boundaries never are.', 'home.ethosText': 'Major Club treats clear communication, mutual consent and personal privacy as essential to social connection.',
  'home.boundary': 'Boundaries are stated clearly', 'home.reporting': 'Reports remain confidential', 'home.control': 'You control your profile data', 'home.reciprocal': 'Interaction is reciprocal',
  'home.faqTitle': 'Common questions', 'home.faq1q': 'Can I browse Major Club without joining?', 'home.faq1a': 'Yes. You can browse public member profiles and the Gazette. An account is required to message, connect and publish.',
  'home.faq2q': 'What information appears on my profile?', 'home.faq2a': 'Only information you choose to share is shown. Contact details used during registration are never published on profile cards.',
  'home.faq3q': 'How is community safety handled?', 'home.faq3a': 'Mutual consent, clearly expressed boundaries and confidential reporting tools are central to the experience.',
  'home.footer': 'A private adult social community centred on privacy, consent and human connection.',
  'right.community': 'Community selections', 'right.verified': 'Verified profiles from the live catalogue', 'right.inspect': 'View', 'right.openAll': 'Open all profiles', 'right.joinTitle': 'A profile gains meaning not only when viewed, but when you take part.', 'right.create': 'Join for free', 'right.feedTitle': 'Discover members', 'right.feedDescription': 'Online and verified members', 'right.profileTitle': 'Similar profiles', 'right.profileDescription': 'Based on location and shared interests', 'right.chatTitle': 'New connections', 'right.chatDescription': 'Members who are online now', 'right.discoveryTitle': 'Community selections', 'right.discoveryDescription': 'Based on affinity and proximity',
  'side.feedContext': 'The latest community posts and visual stories.', 'side.registryContext': 'Verified members, couples and selected profiles.', 'side.chatContext': 'End-to-end encrypted conversations and private salons.', 'side.profileContext': 'Your profile, preferences and privacy settings.', 'side.eventsContext': 'Exclusive salons, private gatherings and calendar.',
  'side.allPosts': 'All posts', 'side.filters': 'Member filters', 'side.priority': 'Priority matches', 'side.women': 'Women', 'side.couples': 'Couples', 'side.regions': 'Regions', 'side.summary': 'Profile & preferences', 'side.profileShortcuts': 'Profile shortcuts', 'side.feedChannels': 'Explore', 'side.chatChannels': 'Conversations', 'side.membership': 'Membership', 'side.verifiedStatus': 'Verified member status', 'side.direct': 'Direct conversations', 'side.encrypted': 'Encrypted', 'side.join': 'Join',
};

const tr: Copy = {
  'nav.portal': 'Ana Sayfa', 'nav.feed': 'Keşfet', 'nav.registry': 'Üyeler', 'nav.chat': 'Mesajlar', 'nav.profile': 'Profil', 'nav.events': 'Etkinlikler', 'nav.members': 'Üyeler', 'nav.salons': 'Salonlar', 'nav.login': 'Giriş', 'nav.loginJoin': 'Giriş Yap / Üye Ol', 'nav.compose': 'Gönderi oluştur',
  'home.eyebrow': 'Major Club · Société Privée', 'home.title': 'Arzunun da bir adabı var.', 'home.intro': 'Yetişkinlerin kendileri gibi insanlarla; mahremiyet, karşılıklı rıza ve zarafet içinde tanıştığı özel sosyal topluluk.', 'home.explore': 'Topluluğu keşfet', 'home.join': 'Ücretsiz katıl', 'home.verified': 'Doğrulanmış profiller', 'home.consent': 'Rıza odaklı topluluk', 'home.privacy': 'Mahremiyet öncelikli',
  'home.peopleTitle': 'Bu gece kimler burada?', 'home.peopleText': 'Çevrimiçi ve doğrulanmış üyeler gerçek üye verilerinden sıralanır; topluluk hareket ettikçe bu seçki de değişir.', 'home.allMembers': 'Tüm üyeler', 'home.pathsTitle': 'İçeri girmenin birden fazla yolu var.', 'home.pathsText': 'Önce insanlara göz at, topluluğun sesini dinle; hazır olduğunda kendi profilini oluştur.',
  'home.registryDescription': 'Doğrulanmış profilleri; şehir, yakınlık ve ortak ilgi alanlarıyla keşfet.', 'home.registryAction': 'Üyelere göz at', 'home.gazetteDescription': 'Topluluğun paylaştığı fotoğraflar, notlar ve açık sohbet başlıkları.', 'home.gazetteAction': 'Akışı incele', 'home.dispatchDescription': 'Bağlantı kurduğun kişilerle hesabına özel, sakin ve doğrudan konuşmalar.', 'home.dispatchAction': 'Mesajlara geç',
  'home.ethosTitle': 'Çekim gizemli olabilir. Sınırlar asla.', 'home.ethosText': 'Major Club; açık iletişimi, karşılıklı rızayı ve kişisel mahremiyeti sosyalleşmenin ayrılmaz bir parçası kabul eder.', 'home.boundary': 'Sınırlar açıkça ifade edilir', 'home.reporting': 'Raporlama gizli yürütülür', 'home.control': 'Profil bilgisi kullanıcı kontrolündedir', 'home.reciprocal': 'Etkileşim karşılıklıdır',
  'home.faqTitle': 'Merak edilenler', 'home.faq1q': 'Üye olmadan Major Club’ı gezebilir miyim?', 'home.faq1a': 'Evet. Herkese açık üye profillerini ve topluluk akışını inceleyebilirsin. Mesaj göndermek, bağlantı kurmak ve içerik paylaşmak için hesap gerekir.', 'home.faq2q': 'Profilimde hangi bilgiler görünür?', 'home.faq2a': 'Yalnızca paylaşmayı seçtiğin bilgiler görünür. Kayıt iletişim bilgileri profil kartlarında yayınlanmaz.', 'home.faq3q': 'Topluluk güvenliği nasıl ele alınıyor?', 'home.faq3a': 'Karşılıklı rıza, açık sınırlar ve gizli şikâyet araçları deneyimin temelidir.', 'home.footer': 'Yetişkinler için mahremiyet, rıza ve insan bağlantısı odaklı özel sosyal topluluk.',
  'right.community': 'Topluluktan seçkiler', 'right.verified': 'Gerçek üye verilerinden doğrulanmış profiller', 'right.inspect': 'İncele', 'right.openAll': 'Tüm profilleri aç', 'right.joinTitle': 'Bir profil yalnızca baktığında değil, katıldığında anlam kazanır.', 'right.create': 'Ücretsiz üye ol', 'right.feedTitle': 'Üyeleri keşfet', 'right.feedDescription': 'Çevrimiçi ve doğrulanmış üyeler', 'right.profileTitle': 'Benzer profiller', 'right.profileDescription': 'Konum ve ortak ilgi alanlarına göre', 'right.chatTitle': 'Yeni bağlantılar', 'right.chatDescription': 'Şu anda çevrimiçi olan üyeler', 'right.discoveryTitle': 'Topluluktan seçkiler', 'right.discoveryDescription': 'Uyum ve yakınlığa göre',
  'side.feedContext': 'Topluluğun en güncel gönderileri ve görsel akışı.', 'side.registryContext': 'Doğrulanmış üyeler, çiftler ve öne çıkan profiller.', 'side.chatContext': 'Uçtan uca şifreli birebir yazışmalar ve özel salonlar.', 'side.profileContext': 'Profilin, tercihlerin ve gizlilik ayarların.', 'side.eventsContext': 'Seçkin buluşmalar, özel salonlar ve ajanda.', 'side.allPosts': 'Tüm Gönderiler', 'side.filters': 'Üye Filtreleri', 'side.priority': 'Öncelikli Eşleşme', 'side.women': 'Kadınlar', 'side.couples': 'Çiftler', 'side.regions': 'Bölgeler', 'side.summary': 'Profil & Tercihler', 'side.profileShortcuts': 'Profil Kısayolları', 'side.feedChannels': 'Keşfet', 'side.chatChannels': 'Sohbetler', 'side.membership': 'Üyelik', 'side.verifiedStatus': 'Doğrulanmış Üye Statüsü', 'side.direct': 'Birebir Sohbetler', 'side.encrypted': 'Şifreli', 'side.join': 'Katıl',
};

const nl: Copy = {
  'nav.portal': 'Start', 'nav.feed': 'Ontdekken', 'nav.registry': 'Leden', 'nav.chat': 'Berichten', 'nav.profile': 'Profiel', 'nav.events': 'Evenementen', 'nav.members': 'Leden', 'nav.salons': 'Salons', 'nav.login': 'Inloggen', 'nav.loginJoin': 'Inloggen / Lid worden', 'nav.compose': 'Bericht plaatsen',
  'home.eyebrow': 'Major Club · Société Privée', 'home.title': 'Verlangen kent zijn eigen etiquette.', 'home.intro': 'Een besloten sociale gemeenschap waar volwassenen gelijkgestemden ontmoeten met privacy, wederzijdse instemming en stijl.', 'home.explore': 'Ontdek de community', 'home.join': 'Gratis deelnemen', 'home.verified': 'Geverifieerde profielen', 'home.consent': 'Instemming centraal', 'home.privacy': 'Privacy voorop',
  'home.peopleTitle': 'Wie is er vanavond?', 'home.peopleText': 'Online geverifieerde leden worden gerangschikt op basis van actuele ledengegevens; de selectie verandert voortdurend.', 'home.allMembers': 'Alle leden', 'home.pathsTitle': 'Er is meer dan één manier om binnen te komen.', 'home.pathsText': 'Bekijk eerst de mensen en luister naar de community; maak je profiel wanneer je er klaar voor bent.',
  'home.registryDescription': 'Ontdek geverifieerde profielen op stad, afstand en gedeelde interesses.', 'home.registryAction': 'Bekijk leden', 'home.gazetteDescription': 'Foto’s, notities en open gesprekken uit de community.', 'home.gazetteAction': 'Bekijk de feed', 'home.dispatchDescription': 'Rustige, directe gesprekken met de mensen met wie je verbinding maakt.', 'home.dispatchAction': 'Naar berichten',
  'home.ethosTitle': 'Aantrekkingskracht mag mysterieus zijn. Grenzen nooit.', 'home.ethosText': 'Major Club ziet duidelijke communicatie, wederzijdse instemming en persoonlijke privacy als de basis van sociaal contact.', 'home.boundary': 'Grenzen worden duidelijk uitgesproken', 'home.reporting': 'Meldingen blijven vertrouwelijk', 'home.control': 'Jij beheert je profielgegevens', 'home.reciprocal': 'Interactie is wederzijds',
  'home.faqTitle': 'Veelgestelde vragen', 'home.faq1q': 'Kan ik Major Club bekijken zonder lid te worden?', 'home.faq1a': 'Ja. Je kunt openbare profielen en de communityfeed bekijken. Voor berichten, connecties en publicaties is een account nodig.', 'home.faq2q': 'Welke informatie staat op mijn profiel?', 'home.faq2a': 'Alleen informatie die je zelf deelt is zichtbaar. Contactgegevens uit de registratie worden niet gepubliceerd.', 'home.faq3q': 'Hoe wordt de community veilig gehouden?', 'home.faq3a': 'Wederzijdse instemming, duidelijke grenzen en vertrouwelijke meldfuncties staan centraal.', 'home.footer': 'Een besloten sociale community voor volwassenen, gericht op privacy, instemming en menselijke verbinding.',
  'right.community': 'Selecties uit de community', 'right.verified': 'Geverifieerde profielen uit de actuele ledenlijst', 'right.inspect': 'Bekijken', 'right.openAll': 'Alle profielen openen', 'right.joinTitle': 'Een profiel krijgt betekenis wanneer je niet alleen kijkt, maar ook deelneemt.', 'right.create': 'Gratis lid worden', 'right.feedTitle': 'Ontdek leden', 'right.feedDescription': 'Online en geverifieerde leden', 'right.profileTitle': 'Vergelijkbare profielen', 'right.profileDescription': 'Op basis van locatie en gedeelde interesses', 'right.chatTitle': 'Nieuwe connecties', 'right.chatDescription': 'Leden die nu online zijn', 'right.discoveryTitle': 'Communityselecties', 'right.discoveryDescription': 'Op basis van affiniteit en afstand',
  'side.feedContext': 'De nieuwste berichten en visuele verhalen uit de community.', 'side.registryContext': 'Geverifieerde leden, koppels en geselecteerde profielen.', 'side.chatContext': 'End-to-end versleutelde gesprekken en privésalons.', 'side.profileContext': 'Je profiel, voorkeuren en privacyinstellingen.', 'side.eventsContext': 'Exclusieve salons, privébijeenkomsten en kalender.', 'side.allPosts': 'Alle berichten', 'side.filters': 'Ledenfilters', 'side.priority': 'Voorkeursmatches', 'side.women': 'Vrouwen', 'side.couples': 'Koppels', 'side.regions': 'Regio’s', 'side.summary': 'Profiel & voorkeuren', 'side.profileShortcuts': 'Profielsnelkoppelingen', 'side.feedChannels': 'Ontdekken', 'side.chatChannels': 'Gesprekken', 'side.membership': 'Lidmaatschap', 'side.verifiedStatus': 'Geverifieerde status', 'side.direct': 'Privégesprekken', 'side.encrypted': 'Versleuteld', 'side.join': 'Deelnemen',
};

const de: Copy = {
  'nav.portal': 'Startseite', 'nav.feed': 'Entdecken', 'nav.registry': 'Mitglieder', 'nav.chat': 'Nachrichten', 'nav.profile': 'Profil', 'nav.events': 'Events', 'nav.members': 'Mitglieder', 'nav.salons': 'Salons', 'nav.login': 'Anmelden', 'nav.loginJoin': 'Anmelden / Beitreten', 'nav.compose': 'Beitrag verfassen',
  'home.eyebrow': 'Major Club · Société Privée', 'home.title': 'Verlangen hat seine eigene Etikette.', 'home.intro': 'Eine private Gemeinschaft, in der Erwachsene Gleichgesinnte mit Diskretion, gegenseitigem Einverständnis und Stil kennenlernen.', 'home.explore': 'Community entdecken', 'home.join': 'Kostenlos beitreten', 'home.verified': 'Verifizierte Profile', 'home.consent': 'Einvernehmen im Mittelpunkt', 'home.privacy': 'Privatsphäre zuerst',
  'home.peopleTitle': 'Wer ist heute Abend hier?', 'home.peopleText': 'Online verifizierte Mitglieder werden anhand aktueller Mitgliederdaten sortiert; die Auswahl verändert sich laufend.', 'home.allMembers': 'Alle Mitglieder', 'home.pathsTitle': 'Es gibt mehr als einen Weg hinein.', 'home.pathsText': 'Sieh dir zunächst Menschen und Community an; erstelle dein Profil, wenn du bereit bist.',
  'home.registryDescription': 'Entdecke verifizierte Profile nach Stadt, Nähe und gemeinsamen Interessen.', 'home.registryAction': 'Mitglieder ansehen', 'home.gazetteDescription': 'Fotos, Notizen und offene Gespräche aus der Community.', 'home.gazetteAction': 'Feed ansehen', 'home.dispatchDescription': 'Ruhige, direkte Gespräche mit Menschen, zu denen du eine Verbindung aufbaust.', 'home.dispatchAction': 'Zu den Nachrichten',
  'home.ethosTitle': 'Anziehung darf geheimnisvoll sein. Grenzen niemals.', 'home.ethosText': 'Major Club versteht klare Kommunikation, gegenseitiges Einverständnis und persönliche Privatsphäre als Grundlage jeder Begegnung.', 'home.boundary': 'Grenzen werden klar benannt', 'home.reporting': 'Meldungen bleiben vertraulich', 'home.control': 'Du kontrollierst deine Profildaten', 'home.reciprocal': 'Interaktion beruht auf Gegenseitigkeit',
  'home.faqTitle': 'Häufige Fragen', 'home.faq1q': 'Kann ich Major Club ohne Mitgliedschaft ansehen?', 'home.faq1a': 'Ja. Öffentliche Profile und der Community-Feed sind einsehbar. Für Nachrichten, Kontakte und Beiträge ist ein Konto erforderlich.', 'home.faq2q': 'Welche Informationen erscheinen in meinem Profil?', 'home.faq2a': 'Nur Informationen, die du selbst teilst, sind sichtbar. Registrierungsdaten werden nicht auf Profilkarten veröffentlicht.', 'home.faq3q': 'Wie wird die Community geschützt?', 'home.faq3a': 'Gegenseitiges Einverständnis, klare Grenzen und vertrauliche Meldemöglichkeiten stehen im Mittelpunkt.', 'home.footer': 'Eine private Erwachsenen-Community für Privatsphäre, Einverständnis und echte Verbindungen.',
  'right.community': 'Auswahl aus der Community', 'right.verified': 'Verifizierte Profile aus der aktuellen Mitgliederliste', 'right.inspect': 'Ansehen', 'right.openAll': 'Alle Profile öffnen', 'right.joinTitle': 'Ein Profil gewinnt Bedeutung, wenn du nicht nur zusiehst, sondern teilnimmst.', 'right.create': 'Kostenlos beitreten', 'right.feedTitle': 'Mitglieder entdecken', 'right.feedDescription': 'Online und verifizierte Mitglieder', 'right.profileTitle': 'Ähnliche Profile', 'right.profileDescription': 'Nach Standort und gemeinsamen Interessen', 'right.chatTitle': 'Neue Kontakte', 'right.chatDescription': 'Mitglieder, die jetzt online sind', 'right.discoveryTitle': 'Community-Auswahl', 'right.discoveryDescription': 'Nach Affinität und Nähe',
  'side.feedContext': 'Die neuesten Beiträge und visuellen Geschichten der Community.', 'side.registryContext': 'Verifizierte Mitglieder, Paare und ausgewählte Profile.', 'side.chatContext': 'Ende-zu-Ende-verschlüsselte Gespräche und private Salons.', 'side.profileContext': 'Dein Profil, deine Präferenzen und Privatsphäre.', 'side.eventsContext': 'Exklusive Salons, private Treffen und Kalender.', 'side.allPosts': 'Alle Beiträge', 'side.filters': 'Mitgliederfilter', 'side.priority': 'Bevorzugte Treffer', 'side.women': 'Frauen', 'side.couples': 'Paare', 'side.regions': 'Regionen', 'side.summary': 'Profil & Präferenzen', 'side.profileShortcuts': 'Profil-Verknüpfungen', 'side.feedChannels': 'Entdecken', 'side.chatChannels': 'Unterhaltungen', 'side.membership': 'Mitgliedschaft', 'side.verifiedStatus': 'Verifizierter Status', 'side.direct': 'Direkte Gespräche', 'side.encrypted': 'Verschlüsselt', 'side.join': 'Beitreten',
};

const fr: Copy = {
  'nav.portal': 'Accueil', 'nav.feed': 'Découvrir', 'nav.registry': 'Membres', 'nav.chat': 'Messages', 'nav.profile': 'Profil', 'nav.members': 'Membres', 'nav.salons': 'Salons', 'nav.login': 'Connexion', 'nav.loginJoin': 'Connexion / Inscription', 'nav.compose': 'Publier',
  'home.eyebrow': 'Major Club · Société Privée', 'home.title': 'Le désir a aussi son étiquette.', 'home.intro': 'Une communauté privée où les adultes rencontrent des personnes partageant leurs affinités, dans le respect de la vie privée, du consentement mutuel et de l’élégance.', 'home.explore': 'Découvrir la communauté', 'home.join': 'Rejoindre gratuitement', 'home.verified': 'Profils vérifiés', 'home.consent': 'Consentement au centre', 'home.privacy': 'Confidentialité prioritaire',
  'home.peopleTitle': 'Qui est là ce soir ?', 'home.peopleText': 'Les membres vérifiés en ligne sont classés à partir des données réelles des membres ; la sélection évolue avec la communauté.', 'home.allMembers': 'Tous les membres', 'home.pathsTitle': 'Il existe plusieurs façons d’entrer.', 'home.pathsText': 'Découvrez d’abord les membres et la voix de la communauté ; créez votre profil lorsque vous êtes prêt.',
  'home.registryDescription': 'Découvrez des profils vérifiés par ville, proximité et centres d’intérêt communs.', 'home.registryAction': 'Voir les membres', 'home.gazetteDescription': 'Photos, notes et conversations ouvertes partagées par la communauté.', 'home.gazetteAction': 'Voir le fil', 'home.dispatchDescription': 'Des conversations calmes et directes avec les personnes auxquelles vous vous liez.', 'home.dispatchAction': 'Voir les messages',
  'home.ethosTitle': 'L’attirance peut être mystérieuse. Les limites, jamais.', 'home.ethosText': 'Major Club considère la communication claire, le consentement mutuel et la vie privée comme essentiels à toute rencontre.', 'home.boundary': 'Les limites sont clairement exprimées', 'home.reporting': 'Les signalements restent confidentiels', 'home.control': 'Vous contrôlez vos données de profil', 'home.reciprocal': 'Les interactions sont réciproques',
  'home.faqTitle': 'Questions fréquentes', 'home.faq1q': 'Puis-je découvrir Major Club sans m’inscrire ?', 'home.faq1a': 'Oui. Les profils publics et le fil de la communauté sont accessibles. Un compte est requis pour écrire, se connecter et publier.', 'home.faq2q': 'Quelles informations apparaissent sur mon profil ?', 'home.faq2a': 'Seules les informations que vous choisissez de partager sont visibles. Les coordonnées d’inscription ne sont jamais publiées.', 'home.faq3q': 'Comment la sécurité est-elle assurée ?', 'home.faq3a': 'Le consentement mutuel, des limites claires et des outils de signalement confidentiels sont au cœur de l’expérience.', 'home.footer': 'Une communauté privée pour adultes fondée sur la confidentialité, le consentement et les liens humains.',
  'right.community': 'Sélection de la communauté', 'right.verified': 'Profils vérifiés issus de la liste des membres', 'right.inspect': 'Voir', 'right.openAll': 'Ouvrir tous les profils', 'right.joinTitle': 'Un profil prend tout son sens lorsque vous ne faites pas que regarder, mais participez.', 'right.create': 'Rejoindre gratuitement', 'right.feedTitle': 'Découvrir des membres', 'right.feedDescription': 'Membres en ligne et vérifiés', 'right.profileTitle': 'Profils similaires', 'right.profileDescription': 'Selon le lieu et les intérêts communs', 'right.chatTitle': 'Nouvelles rencontres', 'right.chatDescription': 'Membres actuellement en ligne', 'right.discoveryTitle': 'Sélection de la communauté', 'right.discoveryDescription': 'Selon les affinités et la proximité',
  'side.feedContext': 'Les dernières publications et histoires visuelles de la communauté.', 'side.registryContext': 'Membres vérifiés, couples et profils sélectionnés.', 'side.chatContext': 'Conversations chiffrées de bout en bout et salons privés.', 'side.profileContext': 'Votre profil, vos préférences et votre confidentialité.', 'side.allPosts': 'Toutes les publications', 'side.filters': 'Filtres des membres', 'side.priority': 'Affinités prioritaires', 'side.women': 'Femmes', 'side.couples': 'Couples', 'side.regions': 'Régions', 'side.summary': 'Profil & préférences', 'side.profileShortcuts': 'Raccourcis du profil', 'side.feedChannels': 'Découvrir', 'side.chatChannels': 'Conversations', 'side.membership': 'Adhésion', 'side.verifiedStatus': 'Statut vérifié', 'side.direct': 'Conversations privées', 'side.encrypted': 'Chiffré', 'side.join': 'Rejoindre',
};

Object.assign(en, {
  'home.heroAlt': 'An elegant adult woman applying perfume in evening attire',
  'feed.compose': 'Create a post', 'feed.photo': 'Photo', 'feed.video': 'Video', 'feed.publish': 'Publish', 'feed.dispatches': 'posts', 'feed.refresh': 'Refresh feed', 'feed.emptyTitle': 'No posts yet', 'feed.emptyText': 'There are no published posts in this selection yet.', 'feed.loading': 'Loading...', 'feed.more': 'Load more posts',
  'discovery.title': 'Members', 'discovery.intro': 'Verified singles and couples, organised by affinity, location and shared interests.', 'discovery.filters': 'Filters', 'discovery.search': 'Search profiles, interests or cities...', 'discovery.allCities': 'All cities', 'discovery.online': 'Online now', 'discovery.attested': 'Verified', 'discovery.women': 'Women', 'discovery.men': 'Men', 'discovery.nonbinary': 'Non-binary', 'discovery.couples': 'Couples', 'discovery.featured': 'Featured profile', 'discovery.patron': 'Host', 'discovery.introAction': 'Send connection request', 'discovery.activeNow': 'Online now',
  'auth.signinTitle': 'Member sign in', 'auth.signupTitle': 'Create your account', 'auth.signinText': 'Access encrypted salons and the private Gazette.', 'auth.signupText': 'Complete your details to join Major Club.', 'auth.name': 'Full name / Pseudonym', 'auth.age': 'Age', 'auth.gender': 'Gender', 'auth.email': 'Private email', 'auth.password': 'Password', 'auth.woman': 'Woman', 'auth.man': 'Man', 'auth.nonbinary': 'Non-binary', 'auth.couple': 'Couple / Duo', 'auth.signin': 'Sign in', 'auth.submit': 'Create account', 'auth.noAccount': 'New here? Join for free', 'auth.hasAccount': 'Already a member? Sign in', 'auth.tagline1': 'Private encounters.', 'auth.tagline2': 'Curated connections.', 'auth.adults': 'Adults only · Privacy first', 'auth.close': 'Close', 'auth.namePlaceholder': 'Your name or chosen name', 'auth.required': 'Enter your email and password.', 'auth.created': 'Your Major Club account is ready.', 'auth.welcome': 'Welcome back', 'auth.failed': 'Sign-in failed. Check your details and try again.',
});
Object.assign(tr, {
  'home.heroAlt': 'Gece kıyafetiyle parfüm kullanan yetişkin bir kadın',
  'feed.compose': 'Bir gönderi oluştur', 'feed.photo': 'Fotoğraf', 'feed.video': 'Video', 'feed.publish': 'Yayınla', 'feed.dispatches': 'gönderi', 'feed.refresh': 'Keşfet akışını yenile', 'feed.emptyTitle': 'Henüz gönderi yok', 'feed.emptyText': 'Bu seçkide henüz yayınlanmış bir gönderi bulunmuyor.', 'feed.loading': 'Yükleniyor...', 'feed.more': 'Daha fazla gönderi yükle',
  'discovery.title': 'Üyeler', 'discovery.intro': 'Doğrulanmış bireyler ve çiftler; uyum, konum ve ortak ilgi alanlarına göre listelenir.', 'discovery.filters': 'Filtreler', 'discovery.search': 'Profil, ilgi alanı veya şehir ara...', 'discovery.allCities': 'Tüm şehirler', 'discovery.online': 'Şu anda çevrimiçi', 'discovery.attested': 'Doğrulanmış', 'discovery.women': 'Kadınlar', 'discovery.men': 'Erkekler', 'discovery.nonbinary': 'Non-binary', 'discovery.couples': 'Çiftler', 'discovery.featured': 'Öne çıkan profil', 'discovery.patron': 'Ev sahibi', 'discovery.introAction': 'Bağlantı isteği gönder', 'discovery.activeNow': 'Şu anda çevrimiçi',
  'auth.signinTitle': 'Üye Girişi', 'auth.signupTitle': 'Hesap Oluştur', 'auth.signinText': 'Özel salonlara ve üye akışına güvenle eriş.', 'auth.signupText': 'Major Club’a katılmak için bilgilerini tamamla.', 'auth.name': 'Ad veya rumuz', 'auth.age': 'Yaş', 'auth.gender': 'Cinsiyet', 'auth.email': 'E-posta adresi', 'auth.password': 'Şifre', 'auth.woman': 'Kadın', 'auth.man': 'Erkek', 'auth.nonbinary': 'Non-binary', 'auth.couple': 'Çift', 'auth.signin': 'Giriş Yap', 'auth.submit': 'Ücretsiz Üye Ol', 'auth.noAccount': 'Henüz üye değil misin? Ücretsiz katıl', 'auth.hasAccount': 'Zaten üye misin? Giriş yap', 'auth.tagline1': 'Özel karşılaşmalar.', 'auth.tagline2': 'Özenle seçilmiş bağlantılar.', 'auth.adults': 'Yalnızca yetişkinler · Mahremiyet öncelikli', 'auth.close': 'Kapat', 'auth.namePlaceholder': 'Adın veya kullanmak istediğin rumuz', 'auth.required': 'E-posta adresini ve şifreni gir.', 'auth.created': 'Major Club hesabın hazır.', 'auth.welcome': 'Tekrar hoş geldin', 'auth.failed': 'Giriş yapılamadı. Bilgilerini kontrol edip tekrar dene.',
});
Object.assign(nl, {
  'home.heroAlt': 'Een elegante volwassen vrouw in avondkleding die parfum aanbrengt',
  'feed.compose': 'Plaats een bericht', 'feed.photo': 'Foto', 'feed.video': 'Video', 'feed.publish': 'Publiceren', 'feed.dispatches': 'berichten', 'feed.refresh': 'Feed vernieuwen', 'feed.emptyTitle': 'Nog geen berichten', 'feed.emptyText': 'In deze selectie zijn nog geen berichten gepubliceerd.', 'feed.loading': 'Laden...', 'feed.more': 'Meer berichten laden',
  'discovery.title': 'Leden', 'discovery.intro': 'Geverifieerde singles en koppels, gerangschikt op affiniteit, locatie en gedeelde interesses.', 'discovery.filters': 'Filters', 'discovery.search': 'Zoek profielen, interesses of steden...', 'discovery.allCities': 'Alle steden', 'discovery.online': 'Nu online', 'discovery.attested': 'Geverifieerd', 'discovery.women': 'Vrouwen', 'discovery.men': 'Mannen', 'discovery.nonbinary': 'Non-binair', 'discovery.couples': 'Koppels', 'discovery.featured': 'Uitgelicht profiel', 'discovery.patron': 'Host', 'discovery.introAction': 'Connectieverzoek sturen', 'discovery.activeNow': 'Nu online',
  'auth.signinTitle': 'Inloggen als lid', 'auth.signupTitle': 'Account aanmaken', 'auth.signinText': 'Krijg toegang tot privésalons en de ledenfeed.', 'auth.signupText': 'Vul je gegevens in om lid te worden van Major Club.', 'auth.name': 'Naam of pseudoniem', 'auth.age': 'Leeftijd', 'auth.gender': 'Gender', 'auth.email': 'E-mailadres', 'auth.password': 'Wachtwoord', 'auth.woman': 'Vrouw', 'auth.man': 'Man', 'auth.nonbinary': 'Non-binair', 'auth.couple': 'Koppel', 'auth.signin': 'Inloggen', 'auth.submit': 'Gratis lid worden', 'auth.noAccount': 'Nog geen lid? Word gratis lid', 'auth.hasAccount': 'Al lid? Log in', 'auth.tagline1': 'Bijzondere ontmoetingen.', 'auth.tagline2': 'Zorgvuldig gekozen connecties.', 'auth.adults': 'Alleen volwassenen · Privacy voorop', 'auth.close': 'Sluiten', 'auth.namePlaceholder': 'Je naam of gekozen pseudoniem', 'auth.required': 'Vul je e-mailadres en wachtwoord in.', 'auth.created': 'Je Major Club-account is klaar.', 'auth.welcome': 'Welkom terug', 'auth.failed': 'Inloggen mislukt. Controleer je gegevens en probeer opnieuw.',
});
Object.assign(de, {
  'home.heroAlt': 'Eine elegante erwachsene Frau in Abendkleidung beim Auftragen von Parfüm',
  'feed.compose': 'Beitrag verfassen', 'feed.photo': 'Foto', 'feed.video': 'Video', 'feed.publish': 'Veröffentlichen', 'feed.dispatches': 'Beiträge', 'feed.refresh': 'Feed aktualisieren', 'feed.emptyTitle': 'Noch keine Beiträge', 'feed.emptyText': 'In dieser Auswahl wurden noch keine Beiträge veröffentlicht.', 'feed.loading': 'Wird geladen...', 'feed.more': 'Weitere Beiträge laden',
  'discovery.title': 'Mitglieder', 'discovery.intro': 'Verifizierte Singles und Paare, geordnet nach Affinität, Standort und gemeinsamen Interessen.', 'discovery.filters': 'Filter', 'discovery.search': 'Profile, Interessen oder Städte suchen...', 'discovery.allCities': 'Alle Städte', 'discovery.online': 'Jetzt online', 'discovery.attested': 'Verifiziert', 'discovery.women': 'Frauen', 'discovery.men': 'Männer', 'discovery.nonbinary': 'Nichtbinär', 'discovery.couples': 'Paare', 'discovery.featured': 'Ausgewähltes Profil', 'discovery.patron': 'Gastgeber', 'discovery.introAction': 'Kontaktanfrage senden', 'discovery.activeNow': 'Jetzt online',
  'auth.signinTitle': 'Mitglieder-Login', 'auth.signupTitle': 'Konto erstellen', 'auth.signinText': 'Greife auf private Salons und den Mitglieder-Feed zu.', 'auth.signupText': 'Vervollständige deine Angaben, um Major Club beizutreten.', 'auth.name': 'Name oder Pseudonym', 'auth.age': 'Alter', 'auth.gender': 'Geschlecht', 'auth.email': 'E-Mail-Adresse', 'auth.password': 'Passwort', 'auth.woman': 'Frau', 'auth.man': 'Mann', 'auth.nonbinary': 'Nichtbinär', 'auth.couple': 'Paar', 'auth.signin': 'Anmelden', 'auth.submit': 'Kostenlos beitreten', 'auth.noAccount': 'Noch kein Mitglied? Kostenlos beitreten', 'auth.hasAccount': 'Schon Mitglied? Anmelden', 'auth.tagline1': 'Besondere Begegnungen.', 'auth.tagline2': 'Sorgfältig ausgewählte Verbindungen.', 'auth.adults': 'Nur für Erwachsene · Privatsphäre zuerst', 'auth.close': 'Schließen', 'auth.namePlaceholder': 'Dein Name oder gewähltes Pseudonym', 'auth.required': 'Gib deine E-Mail-Adresse und dein Passwort ein.', 'auth.created': 'Dein Major Club-Konto ist bereit.', 'auth.welcome': 'Willkommen zurück', 'auth.failed': 'Anmeldung fehlgeschlagen. Prüfe deine Angaben und versuche es erneut.',
});
Object.assign(fr, {
  'home.heroAlt': 'Une femme adulte élégante en tenue de soirée appliquant du parfum',
  'feed.compose': 'Créer une publication', 'feed.photo': 'Photo', 'feed.video': 'Vidéo', 'feed.publish': 'Publier', 'feed.dispatches': 'publications', 'feed.refresh': 'Actualiser le fil', 'feed.emptyTitle': 'Aucune publication', 'feed.emptyText': 'Aucune publication n’a encore été publiée dans cette sélection.', 'feed.loading': 'Chargement...', 'feed.more': 'Charger plus de publications',
  'discovery.title': 'Membres', 'discovery.intro': 'Célibataires et couples vérifiés, classés par affinités, lieu et centres d’intérêt communs.', 'discovery.filters': 'Filtres', 'discovery.search': 'Rechercher des profils, intérêts ou villes...', 'discovery.allCities': 'Toutes les villes', 'discovery.online': 'En ligne maintenant', 'discovery.attested': 'Vérifié', 'discovery.women': 'Femmes', 'discovery.men': 'Hommes', 'discovery.nonbinary': 'Non-binaire', 'discovery.couples': 'Couples', 'discovery.featured': 'Profil à la une', 'discovery.patron': 'Hôte', 'discovery.introAction': 'Envoyer une demande de contact', 'discovery.activeNow': 'En ligne maintenant',
  'auth.signinTitle': 'Connexion membre', 'auth.signupTitle': 'Créer un compte', 'auth.signinText': 'Accédez aux salons privés et au fil des membres.', 'auth.signupText': 'Complétez vos informations pour rejoindre Major Club.', 'auth.name': 'Nom ou pseudonyme', 'auth.age': 'Âge', 'auth.gender': 'Genre', 'auth.email': 'Adresse e-mail', 'auth.password': 'Mot de passe', 'auth.woman': 'Femme', 'auth.man': 'Homme', 'auth.nonbinary': 'Non-binaire', 'auth.couple': 'Couple', 'auth.signin': 'Se connecter', 'auth.submit': 'Rejoindre gratuitement', 'auth.noAccount': 'Pas encore membre ? Rejoignez-nous gratuitement', 'auth.hasAccount': 'Déjà membre ? Se connecter', 'auth.tagline1': 'Rencontres privilégiées.', 'auth.tagline2': 'Connexions choisies avec soin.', 'auth.adults': 'Adultes uniquement · Confidentialité prioritaire', 'auth.close': 'Fermer', 'auth.namePlaceholder': 'Votre nom ou pseudonyme', 'auth.required': 'Saisissez votre e-mail et votre mot de passe.', 'auth.created': 'Votre compte Major Club est prêt.', 'auth.welcome': 'Bon retour parmi nous', 'auth.failed': 'Connexion impossible. Vérifiez vos informations et réessayez.',
});

Object.assign(en, {
  'auth.verifyEmail': 'Check your inbox to confirm your email. You can sign in after confirmation.',
  'auth.signupFailed': 'Your account could not be created. Please try again.',
  'auth.emailExists': 'An account already exists for this email. Sign in instead.',
  'auth.passwordShort': 'Use a password with at least 6 characters.',
  'auth.rateLimit': 'Too many attempts. Wait a moment and try again.',
  'auth.invalidEmail': 'Enter a valid email address.',
  'auth.invalidCredentials': 'The email or password is incorrect.',
  'auth.emailUnconfirmed': 'Confirm your email before signing in.',
  'auth.profileFailed': 'Your account is ready, but the profile could not be created. Please sign in again.',
  'auth.signupDisabled': 'New registrations are temporarily unavailable.',
  'auth.confirmationEmailFailed': 'We could not send the confirmation email. Please try again shortly.',
  'auth.networkError': 'The authentication service could not be reached. Check your connection and try again.',
});
Object.assign(tr, {
  'auth.verifyEmail': 'E-posta adresine bir doğrulama bağlantısı gönderdik. Onayladıktan sonra giriş yapabilirsin.',
  'auth.signupFailed': 'Hesabın oluşturulamadı. Lütfen tekrar dene.',
  'auth.emailExists': 'Bu e-posta adresiyle zaten bir hesap var. Giriş yapmayı dene.',
  'auth.passwordShort': 'En az 6 karakterli bir şifre kullan.',
  'auth.rateLimit': 'Çok fazla deneme yapıldı. Biraz bekleyip tekrar dene.',
  'auth.invalidEmail': 'Geçerli bir e-posta adresi gir.',
  'auth.invalidCredentials': 'E-posta adresi veya şifre hatalı.',
  'auth.emailUnconfirmed': 'Giriş yapmadan önce e-posta adresini doğrula.',
  'auth.profileFailed': 'Hesabın hazır ancak profil oluşturulamadı. Lütfen tekrar giriş yap.',
  'auth.signupDisabled': 'Yeni kayıtlar geçici olarak kullanılamıyor.',
  'auth.confirmationEmailFailed': 'Doğrulama e-postası gönderilemedi. Lütfen kısa süre sonra tekrar dene.',
  'auth.networkError': 'Kimlik doğrulama servisine ulaşılamadı. Bağlantını kontrol edip tekrar dene.',
});
Object.assign(nl, {
  'auth.verifyEmail': 'Controleer je inbox en bevestig je e-mailadres. Daarna kun je inloggen.',
  'auth.signupFailed': 'Je account kon niet worden aangemaakt. Probeer het opnieuw.',
  'auth.emailExists': 'Er bestaat al een account met dit e-mailadres. Log in.',
  'auth.passwordShort': 'Gebruik een wachtwoord van minimaal 6 tekens.',
  'auth.rateLimit': 'Te veel pogingen. Wacht even en probeer het opnieuw.',
  'auth.invalidEmail': 'Vul een geldig e-mailadres in.',
  'auth.invalidCredentials': 'Het e-mailadres of wachtwoord is onjuist.',
  'auth.emailUnconfirmed': 'Bevestig je e-mailadres voordat je inlogt.',
  'auth.profileFailed': 'Je account is klaar, maar het profiel kon niet worden aangemaakt. Log opnieuw in.',
  'auth.signupDisabled': 'Nieuwe registraties zijn tijdelijk niet beschikbaar.',
  'auth.confirmationEmailFailed': 'De bevestigingsmail kon niet worden verzonden. Probeer het zo opnieuw.',
  'auth.networkError': 'De authenticatieservice is niet bereikbaar. Controleer je verbinding en probeer opnieuw.',
});
Object.assign(de, {
  'auth.verifyEmail': 'Prüfe deinen Posteingang und bestätige deine E-Mail-Adresse. Danach kannst du dich anmelden.',
  'auth.signupFailed': 'Dein Konto konnte nicht erstellt werden. Bitte versuche es erneut.',
  'auth.emailExists': 'Für diese E-Mail-Adresse gibt es bereits ein Konto. Bitte melde dich an.',
  'auth.passwordShort': 'Verwende ein Passwort mit mindestens 6 Zeichen.',
  'auth.rateLimit': 'Zu viele Versuche. Warte kurz und versuche es erneut.',
  'auth.invalidEmail': 'Gib eine gültige E-Mail-Adresse ein.',
  'auth.invalidCredentials': 'E-Mail-Adresse oder Passwort ist falsch.',
  'auth.emailUnconfirmed': 'Bestätige deine E-Mail-Adresse, bevor du dich anmeldest.',
  'auth.profileFailed': 'Dein Konto ist bereit, aber das Profil konnte nicht erstellt werden. Melde dich erneut an.',
  'auth.signupDisabled': 'Neue Registrierungen sind vorübergehend nicht verfügbar.',
  'auth.confirmationEmailFailed': 'Die Bestätigungs-E-Mail konnte nicht gesendet werden. Versuche es gleich erneut.',
  'auth.networkError': 'Der Authentifizierungsdienst ist nicht erreichbar. Prüfe deine Verbindung und versuche es erneut.',
});
Object.assign(fr, {
  'auth.verifyEmail': 'Consultez votre boîte de réception et confirmez votre adresse e-mail. Vous pourrez ensuite vous connecter.',
  'auth.signupFailed': 'Votre compte n’a pas pu être créé. Veuillez réessayer.',
  'auth.emailExists': 'Un compte existe déjà pour cette adresse e-mail. Connectez-vous.',
  'auth.passwordShort': 'Utilisez un mot de passe d’au moins 6 caractères.',
  'auth.rateLimit': 'Trop de tentatives. Attendez un instant puis réessayez.',
  'auth.invalidEmail': 'Saisissez une adresse e-mail valide.',
  'auth.invalidCredentials': 'L’adresse e-mail ou le mot de passe est incorrect.',
  'auth.emailUnconfirmed': 'Confirmez votre adresse e-mail avant de vous connecter.',
  'auth.profileFailed': 'Votre compte est prêt, mais le profil n’a pas pu être créé. Reconnectez-vous.',
  'auth.signupDisabled': 'Les nouvelles inscriptions sont temporairement indisponibles.',
  'auth.confirmationEmailFailed': 'L’e-mail de confirmation n’a pas pu être envoyé. Réessayez dans un instant.',
  'auth.networkError': 'Le service d’authentification est inaccessible. Vérifiez votre connexion et réessayez.',
});

Object.assign(en, {
  'auth.forgotPassword': 'Forgot password?', 'auth.resetTitle': 'Reset your password', 'auth.resetText': 'Enter your email and we will send you a secure reset link.', 'auth.sendReset': 'Send reset link', 'auth.resetSent': 'Password reset link sent. Check your inbox.', 'auth.resetFailed': 'The password reset email could not be sent. Please try again shortly.', 'auth.recoveryTitle': 'Choose a new password', 'auth.recoveryText': 'Create a new password for your Major Club account.', 'auth.confirmPassword': 'Confirm password', 'auth.updatePassword': 'Update password', 'auth.passwordUpdated': 'Your password has been updated.', 'auth.passwordMismatch': 'The passwords do not match.', 'auth.showPassword': 'Show password', 'auth.hidePassword': 'Hide password', 'auth.backToSignIn': 'Back to sign in', 'auth.emailRequired': 'Enter your email address.', 'auth.passwordRequired': 'Enter and confirm your new password.',
});
Object.assign(tr, {
  'auth.forgotPassword': 'Şifremi unuttum', 'auth.resetTitle': 'Şifreni sıfırla', 'auth.resetText': 'E-posta adresini gir; güvenli sıfırlama bağlantısını gönderelim.', 'auth.sendReset': 'Sıfırlama bağlantısı gönder', 'auth.resetSent': 'Şifre sıfırlama bağlantısı gönderildi. Gelen kutunu kontrol et.', 'auth.resetFailed': 'Şifre sıfırlama e-postası gönderilemedi. Lütfen kısa süre sonra tekrar dene.', 'auth.recoveryTitle': 'Yeni şifreni belirle', 'auth.recoveryText': 'Major Club hesabın için yeni bir şifre oluştur.', 'auth.confirmPassword': 'Şifreyi doğrula', 'auth.updatePassword': 'Şifreyi güncelle', 'auth.passwordUpdated': 'Şifren başarıyla güncellendi.', 'auth.passwordMismatch': 'Şifreler birbiriyle eşleşmiyor.', 'auth.showPassword': 'Şifreyi göster', 'auth.hidePassword': 'Şifreyi gizle', 'auth.backToSignIn': 'Giriş ekranına dön', 'auth.emailRequired': 'E-posta adresini gir.', 'auth.passwordRequired': 'Yeni şifreni gir ve doğrula.',
});
Object.assign(nl, {
  'auth.forgotPassword': 'Wachtwoord vergeten?', 'auth.resetTitle': 'Wachtwoord herstellen', 'auth.resetText': 'Vul je e-mailadres in voor een beveiligde herstellink.', 'auth.sendReset': 'Herstellink verzenden', 'auth.resetSent': 'De herstellink is verzonden. Controleer je inbox.', 'auth.resetFailed': 'De e-mail voor wachtwoordherstel kon niet worden verzonden. Probeer het zo opnieuw.', 'auth.recoveryTitle': 'Kies een nieuw wachtwoord', 'auth.recoveryText': 'Maak een nieuw wachtwoord voor je account.', 'auth.confirmPassword': 'Wachtwoord bevestigen', 'auth.updatePassword': 'Wachtwoord bijwerken', 'auth.passwordUpdated': 'Je wachtwoord is bijgewerkt.', 'auth.passwordMismatch': 'De wachtwoorden komen niet overeen.', 'auth.showPassword': 'Wachtwoord tonen', 'auth.hidePassword': 'Wachtwoord verbergen', 'auth.backToSignIn': 'Terug naar inloggen', 'auth.emailRequired': 'Vul je e-mailadres in.', 'auth.passwordRequired': 'Vul je nieuwe wachtwoord in en bevestig het.',
});
Object.assign(de, {
  'auth.forgotPassword': 'Passwort vergessen?', 'auth.resetTitle': 'Passwort zurücksetzen', 'auth.resetText': 'Gib deine E-Mail-Adresse für einen sicheren Link ein.', 'auth.sendReset': 'Link senden', 'auth.resetSent': 'Der Link wurde gesendet. Prüfe deinen Posteingang.', 'auth.resetFailed': 'Die E-Mail zum Zurücksetzen des Passworts konnte nicht gesendet werden. Versuche es gleich erneut.', 'auth.recoveryTitle': 'Neues Passwort wählen', 'auth.recoveryText': 'Erstelle ein neues Passwort für dein Konto.', 'auth.confirmPassword': 'Passwort bestätigen', 'auth.updatePassword': 'Passwort aktualisieren', 'auth.passwordUpdated': 'Dein Passwort wurde aktualisiert.', 'auth.passwordMismatch': 'Die Passwörter stimmen nicht überein.', 'auth.showPassword': 'Passwort anzeigen', 'auth.hidePassword': 'Passwort ausblenden', 'auth.backToSignIn': 'Zurück zur Anmeldung', 'auth.emailRequired': 'Gib deine E-Mail-Adresse ein.', 'auth.passwordRequired': 'Gib dein neues Passwort ein und bestätige es.',
});
Object.assign(fr, {
  'auth.forgotPassword': 'Mot de passe oublié ?', 'auth.resetTitle': 'Réinitialiser le mot de passe', 'auth.resetText': 'Saisissez votre e-mail pour recevoir un lien sécurisé.', 'auth.sendReset': 'Envoyer le lien', 'auth.resetSent': 'Le lien a été envoyé. Consultez votre boîte de réception.', 'auth.resetFailed': 'L’e-mail de réinitialisation du mot de passe n’a pas pu être envoyé. Réessayez dans un instant.', 'auth.recoveryTitle': 'Choisir un nouveau mot de passe', 'auth.recoveryText': 'Créez un nouveau mot de passe pour votre compte.', 'auth.confirmPassword': 'Confirmer le mot de passe', 'auth.updatePassword': 'Mettre à jour', 'auth.passwordUpdated': 'Votre mot de passe a été mis à jour.', 'auth.passwordMismatch': 'Les mots de passe ne correspondent pas.', 'auth.showPassword': 'Afficher le mot de passe', 'auth.hidePassword': 'Masquer le mot de passe', 'auth.backToSignIn': 'Retour à la connexion', 'auth.emailRequired': 'Saisissez votre adresse e-mail.', 'auth.passwordRequired': 'Saisissez et confirmez votre nouveau mot de passe.',
});

const catalogs: Record<SupportedLanguage, Copy> = { tr, en, nl, de, fr };
const LanguageContext = createContext({ language: 'en' as SupportedLanguage, t: (key: string) => en[key] || key });

export const LanguageProvider: React.FC<React.PropsWithChildren<{ language: SupportedLanguage }>> = ({ language, children }) => {
  const value = useMemo(() => ({ language, t: (key: string) => catalogs[language][key] || en[key] || key }), [language]);
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => useContext(LanguageContext);
